version: "3.4"

services:
  drink-delivery-api:
    tty: true
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/app"
    environment:
      - ENV_FOR_DYNACONF=development
    ports:
      - "5000:5000"