name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: make docker/build

      - name: Lint project
        run: make docker/lint

      - name: Unit tests
        run: make docker/test-unit

      - name: Integration tests
        run: make docker/test-integration